### PR TITLE
Upgrade to Gradle 8.0.1

### PR DESCRIPTION
**Pull request by sschuberth**

### CODE REVIEW

**Comment by sschuberth** [comment]
@melix, I'm also working on converting the project to Kotlin. Would you be interesting in those changes as well?

**Comment by melix** [comment]
> @melix, I'm also working on converting the project to Kotlin. Would you be interesting in those changes as well?

Thanks for the PR! No I'm not interested in a Kotlin version. I am not even sure it's a good idea to involve Kotlin with the TAPI, since this would mean more things would be on the wire between the client and the server (because of serialization), I think, so less performant.

**Comment by sschuberth** [comment]
> No I'm not interested in a Kotlin version.

Ok, understood.

> I am not even sure it's a good idea to involve Kotlin with the TAPI

FYI, for now, I've only converted the `inspector` and `model` modules to avoid the plugin itself to depend e.g. on the Kotlin `stdlib`, which would indeed complicate things. But I'll keep this for myself then 😁 

PS: I realize this project is a bit older. Is there by now a newer / better approach that you know of to "inject" plugins to arbitrary Gradle builds, which also allowing to debug the plugin code?

**Comment by melix** [comment]
>  Is there by now a newer / better approach that you know of to "inject" plugins to arbitrary Gradle builds, which also allowing to debug the plugin code?

There isn't AFAIK.

**Comment by sschuberth** [comment]
BTW, I just realized that before Gradle 8 the output was

```
> Task :inspector:run
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/inspector/build/libs/inspector.jar
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/inspector/build/distributions/inspector.zip
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/inspector/build/distributions/inspector.tar
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/model/build/libs/model.jar
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/plugin/build/libs/plugin.jar
```

whereas with Gradle 8 it's

```
> Task :inspector:run
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/inspector/build/libs/inspector.jar
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/inspector/build/distributions/inspector.zip
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/inspector/build/distributions/inspector.tar
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/inspector/src/main/resources
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/inspector/src/main/java
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/inspector/build/test-results/test/binary
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/model/build/libs/model.jar
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/model/src/main/resources
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/model/src/main/java
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/model/build/test-results/test/binary
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/plugin/build/libs/plugin.jar
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/plugin/src/main/resources
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/plugin/src/main/java
artifact = /home/sebastian/Development/GitHub/melix/gradle-tapi-demo-artifacts/plugin/build/test-results/test/binary
```

So there suddenly seem to be more artifacts... not sure if that's expected.

**Comment by melix** [comment]
It is totally expected to have more artifacts since Gradle exposes more variants to consumers now.

**Comment by melix** [comment]
Would you mind rebasing on top of `master` so that I can run the wrapper validation action?

**Comment by sschuberth** [comment]
> Would you mind rebasing on top of `master` so that I can run the wrapper validation action?

Done. Plus I've added the `distributionSha256Sum`.

**Pull request merged**
